#!/usr/bin/env bash

function error() {
    echo "$@" >> /dev/stderr
    exit 1
}

function show-usage() {
cat << EOD
NAME
       git-branch-trash - Move a branch to trash box

SYNOPSIS
       git branch-trash <branch>

DESCRIPTION
       Append "trash/" to the branch name.

OPTIONS
       -h, --help
           Show this description.

EXAMPLES
       When
           $ git branch-trash branch1
       executed, branch1 is deleted and trash/branch1 is created.
       Each HEAD is exactly the same.
       If you want to pick up that branch from trash box, simply move it as
       below command.
           $ git branch -m trash/branch1 branch1
EOD
}

OPTIONS=()
for OPTION in "$@"; do
    case "$OPTION" in
        "-h" )
            # --helpはgit本体のコマンドがmanコマンドへ変換してしまうようで
            # このようなオリジナルのコマンドでは使用できない(git側の微妙な仕様)
            show-usage
            exit
            ;;
        * )
            OPTIONS+=("$OPTION")
            ;;
    esac
done

if [ ${#OPTIONS[@]} == 0 ]; then
    show-usage
    exit 1;
else
    which git >> /dev/null
    if [ $? != 0 ]; then
        error "git command does not exists"
    fi
fi

